export const APP_CONFIG_KEY = {
    BREVO_API_KEY: 'BREVO_API_KEY',
    BREVO_SENDER_EMAIL: 'BREVO_SENDER_EMAIL',
    BREVO_SENDER_NAME: 'BREVO_SENDER_NAME',
    // SEO Global
    SEO_GLOBAL_TITLE: 'SEO_GLOBAL_TITLE',
    SEO_GLOBAL_DESCRIPTION: 'SEO_GLOBAL_DESCRIPTION',
    SEO_GLOBAL_KEYWORDS: 'SEO_GLOBAL_KEYWORDS',
    SEO_GLOBAL_OG_IMAGE: 'SEO_GLOBAL_OG_IMAGE',
    // Fase 5: Cloudinary para certificados PDF
    CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
    CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
    CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
    // Fase 6: Daily.co para aulas sincrónicas
    DAILY_API_KEY: 'DAILY_API_KEY',
    DAILY_WEBHOOK_SECRET: 'DAILY_WEBHOOK_SECRET',
} as const;

export type AppConfigKey = (typeof APP_CONFIG_KEY)[keyof typeof APP_CONFIG_KEY];
