export const APP_CONFIG_KEY = {
    BREVO_API_KEY: 'BREVO_API_KEY',
    BREVO_SENDER_EMAIL: 'BREVO_SENDER_EMAIL',
    BREVO_SENDER_NAME: 'BREVO_SENDER_NAME',
    // SEO Global
    SEO_GLOBAL_TITLE: 'SEO_GLOBAL_TITLE',
    SEO_GLOBAL_DESCRIPTION: 'SEO_GLOBAL_DESCRIPTION',
    SEO_GLOBAL_KEYWORDS: 'SEO_GLOBAL_KEYWORDS',
    SEO_GLOBAL_OG_IMAGE: 'SEO_GLOBAL_OG_IMAGE',
} as const;

export type AppConfigKey = (typeof APP_CONFIG_KEY)[keyof typeof APP_CONFIG_KEY];
